enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
riplib = true

patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "latest"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
rv-brand = "ReVanced Extended"
included-patches = "'Return YouTube Username'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF111111 -OlightThemeBackgroundColor=#FFF9F9F9"
build-mode = "both"
version = "19.47.53"

[YouTube-Music-Extended]
app-name = "YouTube Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
rv-brand = "ReVanced Extended"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
included-patches = "'Visual preferences icons for YouTube Music' 'Return YouTube Username'"
arch = "arm64-v8a"
build-mode = "both"
version = "8.30.54"
